# Generated by Django 2.0.1 on 2018-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=127, verbose_name='Name')),
                ('user_email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('user_salt', models.CharField(max_length=15)),
                ('user_password_hash', models.CharField(max_length=255)),
                ('user_phone_number', models.CharField(max_length=32, verbose_name='Phone Number')),
                ('user_2FA_code', models.CharField(max_length=15)),
                ('user_is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
